name: uddoygi
description: A smart ERP system for company management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  path_provider: ^2.1.2

  # State & Form
  provider: ^6.1.1
  flutter_form_builder: ^10.0.1
  flutter_hooks: ^0.21.2
  excel: ^2.0.6
  table_calendar: ^3.0.9
  share_plus: ^12.0.1
  google_sign_in: ^5.2.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0

  # UI & UX
  carousel_slider: ^5.1.1
  fl_chart: ^0.66.2     # ✅ Used for pie chart
  iconsax: ^0.0.8
  pie_chart: ^5.4.0
  qr_flutter: ^4.1.0
  flutter_email_sender: ^8.0.0
  mailer: ^6.1.0
  font_awesome_flutter: ^10.7.0
  intl_phone_field: ^3.2.0
  google_fonts: ^6.3.1
  auto_size_text: ^3.0.0
  mime: ^2.0.0
  csc_picker: ^0.2.7
  cloud_functions: ^6.0.3
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.5.0
  # Utilities
  http: ^1.2.1
  shared_preferences: ^2.2.2
  file_picker: ^10.2.0
  image_picker: ^1.0.7
  go_router: ^16.0.0
  intl: ^0.20.2
  pdf: ^3.10.4
  printing: ^5.11.0
  permission_handler: ^12.0.1
  image_gallery_saver_plus: ^4.0.1
  video_player: ^2.7.2
  url_launcher: ^6.2.5
  uuid: ^4.5.1
  path: ^1.8.3
  image_cropper: ^11.0.0
  csv: ^5.1.1
  cross_file:      any
  flutter_animate: ^4.5.2
  circle_flags: ^5.0.1        # country flags (ISO-2 codes)
  country_picker: ^2.0.20
  device_info_plus: ^12.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4  # ✅ Used for icon generation

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # ✅ Your icon path

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/               # ✅ Add this
    - assets/config.json
    - assets/videos/login_bg.mp4
